# -*- coding: utf-8 -*-
"""Movie Recommendation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NTeTeBpAw6cwSi0BcQ5W4BiA4xkMJFwJ
"""

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from difflib import get_close_matches

print("Libraries loaded")


FILE_PATH = "/content/movies.csv"

def load_data():
    movies = pd.read_csv(FILE_PATH, on_bad_lines='skip')

    # Convert everything to string
    movies = movies.astype(str)

    # Normalize column names
    movies.columns = [c.strip().lower() for c in movies.columns]

    # Ensure required columns exist
    needed = ['title', 'genres', 'overview', 'keywords', 'cast', 'director']
    for col in needed:
        if col not in movies.columns:
            movies[col] = ""

    movies = movies.fillna("")
    return movies

movies = load_data()
print("\n✔ Dataset loaded successfully!")
print("Number of movies:", len(movies))

def combine_text(row):
    return (
        row['title'] + " " +
        row['genres'] + " " +
        row['keywords'] + " " +
        row['cast'] + " " +
        row['director'] + " " +
        row['overview']
    )

movies["combined"] = movies.apply(combine_text, axis=1)
print("\n✔ Combined text column created!")

# TF-IDF
def build_similarity(df):
    print("\n⏳ Building TF-IDF similarity matrix (may take a moment)…")
    tfidf = TfidfVectorizer(stop_words='english', max_features=5000)
    matrix = tfidf.fit_transform(df["combined"])
    sim = cosine_similarity(matrix)
    print("✔ Similarity matrix created!")
    return sim

similarity = build_similarity(movies)

# Recommend Function
def recommend(movie_name, top_k=5):
    movie_name = movie_name.lower().strip()
    titles = movies["title"].str.lower().tolist()

    match = get_close_matches(movie_name, titles, n=1, cutoff=0.6)
    if not match:
        return None  # movie not found

    idx = titles.index(match[0])

    scores = list(enumerate(similarity[idx]))
    scores_sorted = sorted(scores, key=lambda x: x[1], reverse=True)[1:top_k+1]

    results = []
    for (movie_idx, score) in scores_sorted:
        results.append({
            "title": movies.iloc[movie_idx]["title"],
            "genres": movies.iloc[movie_idx]["genres"],
            "score": round(float(score), 3)
        })
    return results

# Get recommendation from user
movie_name = input("\n🎬 Enter a movie name: ")

result = recommend(movie_name)

if result is None:
    print(f"\n❌ Movie '{movie_name}' not found in dataset.")

else:
    print(f"\n🎉 Recommendations similar to '{movie_name}':\n")
    for i, r in enumerate(result, start=1):
        print(f"{i}. {r['title']} — {r['genres']}")


# ==================================================
# STEP 7 — ADD MOVIE TO DATASET IF NOT FOUND
# ==================================================
if result is None:
    print("\n👇 Let's add this movie to the dataset.")

    title = input("Movie Title: ")
    genres = input("Genres: ")
    overview = input("Overview: ")
    keywords = input("Keywords: ")
    cast = input("Cast: ")
    director = input("Director: ")

    new_row = {
        "title": title,
        "genres": genres,
        "overview": overview,
        "keywords": keywords,
        "cast": cast,
        "director": director
    }

    movies = pd.concat([movies, pd.DataFrame([new_row])], ignore_index=True)
    movies.to_csv(FILE_PATH, index=False)

    print("\n✔ Movie added successfully to CSV!")

    # Rebuild combined text & similarity
    movies["combined"] = movies.apply(combine_text, axis=1)
    similarity = build_similarity(movies)

    print("\n🔁 Dataset updated!")


# ==================================================
# STEP 8 — TRY AGAIN
# ==================================================
movie_name = input("\n🔎 Enter the movie name again for recommendations: ")

result = recommend(movie_name)

if result is None:
    print("\n❌ Movie still not found.")
else:
    print(f"\n🎬 Recommendations for '{movie_name}':\n")
    for i, r in enumerate(result, start=1):
        print(f"{i}. {r['title']} — {r['genres']}")



import heapq

# 1. Setup Goal and Moves
GOAL = "123804765"
# Which indexes can '0' swap with
MOVES = {
    0: (1, 3),    1: (0, 2, 4),    2: (1, 5),
    3: (0, 4, 6), 4: (1, 3, 5, 7), 5: (2, 4, 8),
    6: (3, 7),    7: (4, 6, 8),    8: (5, 7)
}

def get_heuristic(state):
    return sum(1 for i in range(9) if state[i] != '0' and state[i] != GOAL[i])

def a_star(start):
    # Priority Queue: (f-score, g-score, current_state, path_history)
    pq = [(get_heuristic(start), 0, start, "")]
    visited = set()

    while pq:
        f, g, current, path = heapq.heappop(pq)

        if current == GOAL:
            return path + current, g

        if current in visited:
            continue
        visited.add(current)

        # Find '0' and generate moves
        zero_idx = current.index("0")
        for move_idx in MOVES[zero_idx]:
            # Swap 0 to create new state
            new_list = list(current)
            new_list[zero_idx], new_list[move_idx] = new_list[move_idx], new_list[zero_idx]
            new_state = "".join(new_list)

            if new_state not in visited:
                new_g = g + 1
                new_f = new_g + get_heuristic(new_state)
                heapq.heappush(pq, (new_f, new_g, new_state, path + current + "\n⬇\n"))

    return "No Solution", 0

start_state = input("Enter start state (e.g., 283164705): ")
path, steps = a_star(start_state)

print("-------------------------")
print(f"Steps Required: {steps}")
print("Path:\n" + path)

#AND
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])
y = np.array([[0], [0], [0], [1]])
weights = np.random.rand(2, 1)
bias = np.random.rand(1)
lr = 0.1  #learning rate
for epoch in range(1000):
    net = np.dot(X, weights) + bias
    out = sigmoid(net)
    error = y - out

    adjustments = error * sigmoid_derivative(out)
    weights += np.dot(X.T, adjustments) * lr
    bias += np.sum(adjustments) * lr

print("Final Output after training (AND):")
print(out)

#XOR:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)

X = np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])
y = np.array([[0],[1],[1],[0]])
w1 = np.random.rand(2, 2)
b1 = np.random.rand(1)
w2 = np.random.rand(2, 1)
b2 = np.random.rand(1)
lr = 0.1

for epoch in range(1000):
    hidden_input = np.dot(X, w1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, w2) + b2
    output = sigmoid(final_input)
    error = y - output
    d_output = error * sigmoid_derivative(output)

    error_hidden = d_output.dot(w2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    w2 += hidden_output.T.dot(d_output) * lr
    b2 += np.sum(d_output) * lr

    w1 += X.T.dot(d_hidden) * lr
    b1 += np.sum(d_hidden) * lr
print("Final Output after training (XOR):")
print(output)

import random
a = float(input("a: "))
b = float(input("b: "))
c = float(input("c: "))

def fitness(x):
    return abs(a*x*x + b*x + c)

def select(pop):
    p1, p2 = random.sample(pop, 2)
    return p1 if fitness(p1) < fitness(p2) else p2

def genetic():
    pop_size = 50
    pop = [random.uniform(-50, 50) for _ in range(pop_size)]
    for _ in range(200):
        new = []
        for _ in range(pop_size):
            p1 = select(pop)
            p2 = select(pop)
            child = (p1 + p2) / 2
            child += random.uniform(-0.5, 0.5)
            new.append(child)
        pop = new
    return min(pop, key=lambda x: fitness(x))

root1 = genetic()
root2 = genetic()

print("Root 1:", root1)
print("Root 2:", root2)

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import sent_tokenize, word_tokenize
data="Welcome to Sarvajanik University. This is the Computer Department."
wt = nltk.word_tokenize(data)
print("Word tokenize:")
print(wt)
st = nltk.sent_tokenize(data)
print('Sentence tokenize:')
print(st)

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
sw = set(stopwords.words('english'))
data1 = ['This', 'is', 'test', 'Run', '.', 'Hope', 'it', 'works', 'perfectly']

filtered_words = [word for word in data1 if word.lower() not in sw]
print("Filtered list:")
print(filtered_words)

from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
pst = PorterStemmer()
x=pst.stem("happier")
lan = LancasterStemmer()
y=lan.stem("happier")
print('porterStemmer:')
print(x)
print('lancasterStemmer:')
print(y)

import nltk
nltk.download('wordnet')

from nltk.stem import WordNetLemmatizer
lem = WordNetLemmatizer()
words = ["mice", "corpora" , "geese", "running", "children",  "better",  "studies"]
for w in words:
    print(w, "->", lem.lemmatize(w))

import nltk
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('punkt')

sent = "This is Vadodara City"
tokens = nltk.word_tokenize(sent)
pos_tags = nltk.pos_tag(tokens)
print("POS tags:")
print(pos_tags)

